This is a relatively minor change to Saltern-2 intended to become a series of updates to the famed map
RonRonstation/ronstation pull request #148
Opened 2024-11-27 07:47 UTC by Sirius-Frost

## About the PR
 
The evacuation center now has a medical station and has generally been refurbished and revamped.

## Why / Balance

This would make evacuating spessmen in bad or critical condition much easier as they can be 'easily' healed when shit hits the fan and accessing the rest of the station, especially medical, becomes difficult if not impossible. I made it this way not only for the aforementioned quality of life feature, but to overall fit the theme of an evacuation center better and make it generally more pleasing to the eye. 
 
## Technical details

There are no code changes.

## Media

![Second](https://github.com/user-attachments/assets/e4c9ce9d-c780-4fc8-88fb-ac6ade1e3c75)
![First](https://github.com/user-attachments/assets/53f5547b-be8c-4c54-a8db-2cfe984f1b4d)

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

None

**Changelog**

:cl:
- add: Medical station to evac w/ minimal supplies and a fun note
- remove: removed Mr. Chang vendor from just below the Chapel
- remove: Removed the chairs in evac. No sitting!
- tweak: Changed tiling in evac
- tweak: Replaced oxygen cabinet and fire cabinet above disposal in evac with a fire extinguisher
- tweak: Replaced vending machine near east hallway to evac with a more themed one with its adjacent poster
- tweak: Replaced all lights in evac with LEDs
- tweak: Replaced signs on the evac docking bays with more appropriately placed/themed ones.
- tweak: Moved the fire extinguisher in the arrivals to evac doorway further into arrivals to prevent having to open the door to access it.

2024-11-28 03:47 UTC, Merrokitsune requested changes
Thank you very much for your first pull-request.

Unfortunately, I spotted some things that don’t seem to be right. Besides, if I may ask nicely, are you trying to update Saltern-2. If not, do you want the map to be put into rotation or not? Just wanted to clear things up.

2024-11-28 12:07 UTC, Sirius-Frost commented
****

> Thank you very much for your first pull-request.
> 
> Unfortunately, I spotted some things that don’t seem to be right. Besides, if I may ask nicely, are you trying to update Saltern-2. If not, do you want the map to be put into rotation or not? Just wanted to clear things up.

Could you specify what doesn't seem right and how I could go about fixing them? 

Ideally, this would in-fact be an update to Saltern-2. I have named it Saltern-3 for ease of cross-referencing while mapping and testing by myself. I'm not sure it would make sense to put it into rotation by itself in its current form, but given my plans to radically alter certain parts of the layout such as the location of the Observatory it might be wiser to plan for it to be its own, separate map. I'd very much appreciate feedback in that regard.

2024-11-28 12:15 UTC, Merrokitsune commented
> Could you specify what doesn't seem right and how I could go about fixing them?

The saltern-3.yml prototype has a misplaced path.

2024-11-28 13:02 UTC, Merrokitsune approved these changes
Sounds good. Now, we’ll see what to do, due to the unique nature of this PR (you’re intent on adding another Saltern that is already in rotation to be put into rotation).

2024-11-28 13:02 UTC, Merrokitsune commented on Resources/Prototypes/Ronstation/Maps/saltern-3.yml
> +  mapPath: C:\Users\SiriusFrost\OneDrive\Desktop\ronstation\Resources\Maps\Ronstation\saltern-3.yml
This path seems to be taking the map from your computer, and not the repository. The path should start like this:
```suggestion
  mapPath: Maps\Ronstation\saltern-3.yml
```

2024-11-28 13:02 UTC, Merrokitsune commented on Resources/Prototypes/Ronstation/Maps/saltern-3.yml
> +  mapPath: C:\Users\SiriusFrost\OneDrive\Desktop\ronstation\Resources\Maps\Ronstation\saltern-3.yml
Resolved by commit 45713e7819117ec20df6b02cf0c558a17f0a93fa.

2024-11-28 13:14 UTC, Sirius-Frost commented
> > …completely move the observatory over to arrivals which would radically change Saltern.
> 
> It would be nice if there was a screenshot for that, so we can see what it is. ;) Anyways, what would the previous location for the obsevatory be?

I haven't done anything so radical yet. This is just a test run so its only what I put in the initial PR that got changed. I was talking to Sad earlier about what could be some potential revisions to the observatory when i get to it.

I felt like putting everything into one PR would make for an all or nothing scenario and I didnt want to spend hours doing that incase the PR didnt get merged for one reason or the other. As for the previous location for the observatory - its still an offshoot of maints below engineering.  its in a VERY peculiar position on the map.

just fixed the mapPath for the second time as well. used the wrong punctuation.

2024-11-28 13:34 UTC, Sirius-Frost commented
> I am terribly sorry for having to request changes again, but it appears that I have been wrong in the map path.
Could you show me what its actually supposed to be again? I tried fixing it but I got it wrong again seemingly.

2024-11-28 13:39 UTC, Merrokitsune commented
> > I am terribly sorry for having to request changes again, but it appears that I have been wrong in the map path.
> 
> Could you show me what its actually supposed to be again? I tried fixing it but I got it wrong again seemingly.

It is supposed to be “/Maps/Ronstation/saltern-3.yml”.

Just a little question, are you able to view suggested changes in my reviews? My reviews should be viewable.
![IMG_6009](https://github.com/user-attachments/assets/d836e765-bccd-43d2-bc0e-fdc13357c01e)

2024-11-28 13:43 UTC, Sirius-Frost commented
> > > I am terribly sorry for having to request changes again, but it appears that I have been wrong in the map path.
> > 
> > 
> > Could you show me what its actually supposed to be again? I tried fixing it but I got it wrong again seemingly.
> 
> It is supposed to be “/Maps/Ronstation/saltern-3.yml”. Take the path from Saltern-2’s prototype as reference. ![IMG_6008](https://private-user-images.githubusercontent.com/145924961/390804240-620c3c4d-6db1-4a7e-986a-920601444963.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDE2MTQsIm5iZiI6MTczMjgwMTMxNCwicGF0aCI6Ii8xNDU5MjQ5NjEvMzkwODA0MjQwLTYyMGMzYzRkLTZkYjEtNGE3ZS05ODZhLTkyMDYwMTQ0NDk2My5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMTM0MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODZiNTJiYTE1MjA0MTUwZjFkNDVhMzc0Yjk2MjIwY2YxYWIxOGNkNTU3MjJiZmM5N2MxNWEwMWUyN2JiMWRiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.fyis3i_AcUt1P4-JRSt8a8Nhp_OsA1iLqe2pBYVEgvw)
> 
> Just a little question, are you able to view suggested changes in my reviews, since I made suggested changes for you to follow? My reviews, as well as the suggested changes, should be viewable. ![IMG_6009](https://private-user-images.githubusercontent.com/145924961/390803840-d836e765-bccd-43d2-bc0e-fdc13357c01e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MDE2MTQsIm5iZiI6MTczMjgwMTMxNCwicGF0aCI6Ii8xNDU5MjQ5NjEvMzkwODAzODQwLWQ4MzZlNzY1LWJjY2QtNDNkMi1iYzBlLWZkYzEzMzU3YzAxZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjhUMTM0MTU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJjYjJiMDc3MDYyZTIwZjJhMzJhNWM3MjJkMWViNjMzYmZmZjQ1YWE1ZGEyNmJhZTJjOTEwZTdlMDM3MDRiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ld76rchXmNKOZFUs96tGoTNXreVvntvYN66If5AbJ6o)

I can see that you requested changes, but i usually cant see the specific review for some reason. i only saw the one you posted at 40 minutes ago

2024-11-28 14:03 UTC, Sirius-Frost commented
```
Failed!  - Failed:     1, Passed:   367, Skipped:     0, Total:   368, Duration: 7 m 23 s - Content.IntegrationTests.dll (net8.0)
Error: Process completed with exit code 1.
```

Oh, cmon.

2024-11-28 14:19 UTC, Merrokitsune commented
> ```
> Failed!  - Failed:     1, Passed:   367, Skipped:     0, Total:   368, Duration: 7 m 23 s - Content.IntegrationTests.dll (net8.0)
> Error: Process completed with exit code 1.
> ```
> 
> Oh, cmon.

It’s okay.
We’re going to discuss what to do with this PR, so please await orders.
However, if you are going to fix this error…
- go to “`Content.Benchmarks/MapLoadBenchmark.cs`” and add “`Saltern-3`” to the “`public static readonly string[] MapsSource = {}`” (should be located in line 43).
- go to }`Content.IntegrationTests/Tests/PostMapInitTest.cs`” and add “`Saltern-3`” to the “`private static readonly string[] GameMaps = {}`” list (should be located in line 46).

2024-11-28 14:31 UTC, Sirius-Frost commented
> > ```
> > Failed!  - Failed:     1, Passed:   367, Skipped:     0, Total:   368, Duration: 7 m 23 s - Content.IntegrationTests.dll (net8.0)
> > Error: Process completed with exit code 1.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Oh, cmon.
> 
> It’s okay. We’re going to discuss what to do with this PR, so please await orders. However, if you are going to fix this error…
> 
> * go to “`Content.Benchmarks/MapLoadBenchmark.cs`” and add “`Saltern-3`” to the “`public static readonly string[] MapsSource = {}`” (should be located in line 43).
> * go to }`Content.IntegrationTests/Tests/PostMapInitTest.cs`” and add “`Saltern-3`” to the “`private static readonly string[] GameMaps = {}`” list (should be located in line 46).

I've done as suggested. Hopefully that fixes the error as you've said. I'll await the councils judgement.

2024-11-28 18:38 UTC, Merrokitsune approved these changes
Forgot to approve, sorry.

2024-11-28 18:38 UTC, Merrokitsune commented on Resources/Prototypes/Ronstation/Maps/saltern-3.yml
> +  mapPath: Resources/Maps/Ronstation/saltern-3.yml
The “Resources” part should be deleted. I’m sorry that I’ve made a mistake in this.
```suggestion
  mapPath: /Maps/Ronstation/saltern-3.yml
```

2024-11-28 18:44 UTC, Merrokitsune requested changes
Hello again, sirius_frost.

After some discussion with staff and community members, we decided that the following are decided:

This should be kept as a general saltern-2 update, not to be a new map to be put into rotation. Why do we need 2 identical maps when you can have 1?

medical bay in evacuation should be replaced with something else, or otherwise removed, for the following reasons:
- Medbay in evac would be abuseable by players, who would simply break in and take the meds stored within that room, even the locked nature of these storage items aren’t enough of a deterrent to put a stop to these activities. At least, medical personnel can bring their medicine to evacuation if needed.
- Evac medbay is already close to the main medbay area (like it takes around 10 seconds to travel from evac medbay to main medbay), so even medical personnel might find it redundant.

As for the replacement, I would recommend something like a help desk with at least 1 first aid kit.

2024-11-28 19:45 UTC, Sirius-Frost commented
> Hello again, sirius_frost.
> 
> After some discussion with staff and community members, we decided that the following are decided:
> 
> This should be kept as a general saltern-2 update, not to be a new map to be put into rotation. Why do we need 2 identical maps when you can have 1?
> 
> medical bay in evacuation should be replaced with something else, or otherwise removed, for the following reasons:
> 
> * Medbay in evac would be abuseable by players, who would simply break in and take the meds stored within that room, even the locked nature of these storage items aren’t enough of a deterrent to put a stop to these activities. At least, medical personnel can bring their medicine to evacuation if needed.
> * Evac medbay is already close to the main medbay area (like it takes around 10 seconds to travel from evac medbay to main medbay), so even medical personnel might find it redundant.
> 
> As for the replacement, I would recommend something like a help desk with at least 1 first aid kit.

Understood. In the screenshots, the only things in the crates are MREs and bodybags. There are no medkits stored there - the paper stamped with the centcomm stamp notifies the player as much. the one medicinal locker and defib is all they have already, and those could be removed too.

I understand if its too close to medbay to warrant it. i was thinking about if there were no power and somebody didnt have a crowbar - itd take far longer to get to the actual medbay. thats why its in evac - to act as emergency medical attention. the idea is that throughout the shift, medical team works to stock it in case of emergency - when youre hanging out in evac you can go ahead and patch everyone up best you can before the shuttle arrives.

as for making a help desk? maybe. albeit i dont see much point having that in evac. id probably just revert it to where theres no desk and you have the setup with all the chairs. maybe make a help desk in arrivals that leads into the dormitories to funnel people that way rather than through evac (which I always found a little odd)

2024-12-01 05:09 UTC, Merrokitsune requested changes
I found a missing coma in line 67 of Content.IntegrationTests/Tests/PostMapInitTest.cs.

Also, I hope I'm not wrong, but...
> This should be kept as a general saltern-2 update, not to be a new map to be put into rotation. Why do we need 2 identical maps when you can have 1?

- https://github.com/RonRonstation/ronstation/pull/148#pullrequestreview-2468715474

So, if you insist on having Saltern-3, I can derotate (and eventually remove) Saltern-2.

2024-12-01 05:53 UTC, Merrokitsune requested changes
Hello, Sirius_Frost.
I have finally checked the map and noticed 3 problems.
1. An amount of space within the evac medbay is empty and lacks air. Perhaps, you forgot to type `fixgridatmos <gridid>` into the console?
2. The directional windows outside the main windows lack tiles to support and will float aimlessly. Besides, it may obstruct the evacuation shuttle from being near.
3. The fact that the window is facing space without any protections might spell disaster and this are may be spaced more often than you can imagine. So, I can recommend either moving the windows back and adding a protection liner, or converting the windows to reinforced walls.

I have an image proof for these. 
![Screenshot from 2024-12-01 12-39-05](https://github.com/user-attachments/assets/cc62fcb0-8998-4839-9ff6-3ef89ad727ed)

On a positive note, the map is up-to-date with the latest Saltern-2.

2024-12-01 05:53 UTC, Merrokitsune commented on Content.IntegrationTests/Tests/PostMapInitTest.cs
>              "Atlas2"
This is the source of the errors.
```suggestion
            "Atlas2",
```

2024-12-01 15:24 UTC, Merrokitsune approved these changes
This can work.

2024-12-02 04:28 UTC, Sirius-Frost commented
I absolutely fucked the push to origin files. attempting to fix.

2024-12-02 05:53 UTC, Merrokitsune approved these changes
It should work now, merging.

2024-12-02 05:53 UTC, merged

2024-12-02 05:55 UTC, Merrokitsune commented
You can delete the branch now.